---
- name: Redis 
  apt:
    name: redis-server
    state: present
  sudo: yes

- name: Python
  apt:
    name: python
    state: present
  sudo: yes

- name: setuptools
  apt:
    name: python-setuptools
    state: present
  sudo: yes

- name: pip
  apt:
    name: python-pip
    state: present
  sudo: yes

- name: redis py
  pip:
    name: redis
  sudo: yes

- name: API lib directory
  file:
    path: /opt/arbitrage
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  sudo: yes

- name: Downloading Fixerio API
  git:
    repo: "https://github.com/Jufik/python-fixer"
    dest: "/opt/arbitrage/fixer-py"
    update: yes
    force: yes
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Installing Fixerio API
  command: "/usr/bin/python setup.py install"
  args:
    chdir: "/opt/arbitrage/fixer-py"
  sudo: yes

- name: Installing Bitso
  pip:
    name: bitso-py
  sudo: yes

- name: Installing cex
  pip:
    name: cex
  sudo: yes

- name: CEX API
  git:
    repo: "https://github.com/AgusRumayor/cex.io-api-python"
    dest: "/opt/arbitrage/cex-py"
    update: yes
    force: yes
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Installing CEX API
  command: "/usr/bin/python setup.py install"
  args:
    chdir: "/opt/arbitrage/cex-py"
  sudo: yes

- name: Downloading Btce API
  git:
    repo: "https://github.com/CodeReclaimers/btce-api"
    dest: "/opt/arbitrage/btce-py"
    update: yes
    force: yes
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Installing Btce API
  command: "/usr/bin/python setup.py install"
  args:
    chdir: "/opt/arbitrage/btce-py"
  sudo: yes

- name: app directory
  file:
    path: "/home/{{ server_user }}/share"
    state: directory
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Downloading Arbitrage
  git:
    repo: "git@gitlab.com:AgusRumayor/arbitrage.git"
    dest: "/home/{{ server_user }}/share/arbitrage"
    update: yes
    force: yes
    key_file: "/home/{{ server_user }}/.ssh/gitlab"
    accept_hostkey: yes
  sudo: yes
  sudo_user: "{{ server_user }}"

- name: Set default config
  copy:
    content="{{config | to_json}}"
    dest="/home/{{ server_user }}/share/arbitrage/config.json"
  sudo: yes
  sudo_user: "{{ server_user }}"
